package com.zephyr.ports.ai;

import java.util.List;
import java.util.Map;

import java.util.logging.Logger;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

import com.fasterxml.jackson.databind.JsonNode;

import reactor.core.publisher.Mono;

@Service
public class OpenAIService {
    Logger logger = Logger.getLogger(OpenAIService.class.getName());

    private final WebClient webClient;

    @Value("${openai.api.key}")
    private String apiKey;

    public OpenAIService(WebClient.Builder builder) {
        this.webClient = builder.baseUrl("https://api.openai.com/v1").build();
    }

    public Mono<String> getGeneratedPortfolio(String prompt) {
        logger.info("apiKey: " + apiKey.length());
        Map<String, Object> body = Map.of(
            "model", "gpt-4o-mini",
            "messages", List.of(
                Map.of("role", "system", "content", 
                    "You are a financial advisor that will provide a list of stocks between 5-30 and percents that add up to 100 provided in the format TCK,20,TCK,30,... the list will be generated by the users prompt"),
                Map.of("role", "user", "content", prompt)
            )
        );

        return webClient.post()
            .uri("/chat/completions")
            .header("Authorization", "Bearer " + apiKey)
            .header("Content-Type", "application/json")
            .bodyValue(body)
            .retrieve()
            .bodyToMono(JsonNode.class)
            .map(json -> json.path("choices").get(0).path("message").path("content").asText());
    }
}